//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaSatisSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_NotaSatisEntities : DbContext
    {
        public Db_NotaSatisEntities()
            : base("name=Db_NotaSatisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Kullanicilar> Tbl_Kullanicilar { get; set; }
        public virtual DbSet<Tbl_Notalar> Tbl_Notalar { get; set; }
        public virtual DbSet<Tbl_Satislar> Tbl_Satislar { get; set; }
    }
}
