//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaSatisSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Notalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Notalar()
        {
            this.Tbl_Satislar = new HashSet<Tbl_Satislar>();
        }
    
        public int NotaID { get; set; }
        public string NotaAd { get; set; }
        public string EserSahibi { get; set; }
        public string Notalayan { get; set; }
        public string NotaDetay { get; set; }
        public string Enstruman { get; set; }
        public decimal Kredi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satislar> Tbl_Satislar { get; set; }
    }
}
