//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotaSatisSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Satislar
    {
        public int SatisID { get; set; }
        public int NotaID { get; set; }
        public int KullaniciID { get; set; }
        public System.DateTime SatisTarihi { get; set; }
        public decimal Ucret { get; set; }
    
        public virtual Tbl_Kullanicilar Tbl_Kullanicilar { get; set; }
        public virtual Tbl_Notalar Tbl_Notalar { get; set; }
    }
}
